=== DashaShestakova/EightTask/src/main/resources/oldCard.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema"
           targetNamespace="http://www.example.com/oldcards"
           xmlns:tns="http://www.example.com/oldcards"
           elementFormDefault="qualified">


    <xsd:element name="old-cards">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="tns:old-card"
                             minOccurs="2"
                             maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>


    <xsd:element name="old-card" type="tns:OldCard" abstract="true"/>
    <xsd:element name="information-old-card" type="tns:InformationOldCard" substitutionGroup="tns:old-card"/>
    <xsd:element name="congratulation-old-card" type="tns:CongratulationOldCard" substitutionGroup="tns:old-card"/>

    <xsd:complexType name="OldCard">
        <xsd:sequence>
            <xsd:element name="id">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:int">
                        <xsd:pattern value="(\d){1,12}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="theme">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="nature"/>
                        <xsd:enumeration value="sports"/>
                        <xsd:enumeration value="religion"/>
                        <xsd:enumeration value="animal"/>
                        <xsd:enumeration value="car"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="type">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="adventure"/>
                        <xsd:enumeration value="holiday"/>
                        <xsd:enumeration value="simple"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="country">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:pattern value="[\D]{1,15}"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="year">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:integer">
                        <xsd:minExclusive value="1900"/>
                        <xsd:maxInclusive value="2020"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="author">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string"/>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="valuable">
                <xsd:simpleType>
                    <xsd:restriction base="xsd:string">
                        <xsd:enumeration value="historical"/>
                        <xsd:enumeration value="collection"/>
                    </xsd:restriction>
                </xsd:simpleType>
            </xsd:element>
            <xsd:element name="was-send" type="xsd:boolean"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="InformationOldCard">
        <xsd:complexContent>
            <xsd:extension base="tns:OldCard">
                <xsd:sequence>
                    <xsd:element name="sender-name" type="xsd:string"/>
                    <xsd:element name="sender-address" type="xsd:string"/>
                    <xsd:element name="information-text" type="xsd:string"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

    <xsd:complexType name="CongratulationOldCard">
        <xsd:complexContent>
            <xsd:extension base="tns:OldCard">
                <xsd:sequence>
                    <xsd:element name="congratulation-text" type="xsd:string"/>
                </xsd:sequence>
            </xsd:extension>
        </xsd:complexContent>
    </xsd:complexType>

</xsd:schema>

=== DashaShestakova/EightTask/target/classes/oldCard.xml
<?xml version="1.0" encoding="UTF-8"?>
<old-cards xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
           xmlns="http://www.example.com/oldcards"
           xs:schemaLocation="http://www.example.com/oldcards oldCard.xsd"
>
    <congratulation-old-card>
        <id>1</id>
        <theme>animal</theme>
        <type>holiday</type>
        <country>France</country>
        <year>2010</year>
        <author>Antonov V.</author>
        <valuable>collection</valuable>
        <was-send>false</was-send>
        <congratulation-text>Happy Birthday</congratulation-text>
    </congratulation-old-card>
    <congratulation-old-card>
        <id>2</id>
        <theme>car</theme>
        <type>holiday</type>
        <country>Spain</country>
        <year>2012</year>
        <author>Gavrilov D.</author>
        <valuable>collection</valuable>
        <was-send>false</was-send>
        <congratulation-text>Happy New Year</congratulation-text>
    </congratulation-old-card>
    <information-old-card>
        <id>3</id>
        <theme>nature</theme>
        <type>adventure</type>
        <country>Belarus</country>
        <year>2001</year>
        <author>Abramova A.</author>
        <valuable>historical</valuable>
        <was-send>true</was-send>
        <sender-name>Ivanov P.</sender-name>
        <sender-address>BY,Minsk, Lenina str., 1</sender-address>
        <information-text>Good Morning</information-text>
    </information-old-card>
    <information-old-card>
        <id>4</id>
        <theme>sports</theme>
        <type>simple</type>
        <country>Russia</country>
        <year>2005</year>
        <author>Alekseeva K.</author>
        <valuable>collection</valuable>
        <was-send>true</was-send>
        <sender-name>Petrov P.</sender-name>
        <sender-address>BY,Moscow, Marksa str., 5</sender-address>
        <information-text>Good Evening</information-text>
    </information-old-card>
</old-cards>
